### PR TITLE
added conversion M/S to KTS

### PR DESCRIPTION
**Pull request by WillemEerland**
I wanted to initialise the speed in "M/S" and found out I couldn't because there was no conversion to KTS. There is now.

### CODE REVIEW

**Comment by bcoconni** [comment]
@andgi 
The abbreviation for the unit of time *second* in the SI units is *"s"* and *m/s* is a SI unit.

Indeed historically the abbreviation "SEC" has been added to JSBSim (to be used with British/Imperial units ?) However *"m/sec"* has always looked weird to me but if you feel that it is a miss, feel free to push a commit.

**Comment by andgi** [comment]
@bcoconni Well, yes, I grew up with SI so that is no news to me :)

Ok, so you propose that we use "S" with SI units and "SEC" with British/Imperial units? There is as far as I know no such consistency currently. "SEC" is used in almost all units in FGXMLElement, I think "S" only occurs in "M/S".

**Comment by bcoconni** [comment]
@andgi 
> Well, yes, I grew up with SI so that is no news to me :)

Sorry there was no offense intended.

>  so you propose that we use "S" with SI units and "SEC" with British/Imperial units?

No I don't. All I am saying is that *I guess* that "SEC" was introduced by people using British units. I am not proposing to modify anything. All I meant was that I can live without "M/SEC" but if you feel that it should be added, go ahead !

> As far as I see "SEC" already occurs in SI-based units RAD/SEC, N/M/SEC, N/M2/SEC2, M/SEC, M4*SEC/KG, N/SEC in FGXMLElement.

There is plenty to say regarding unit naming in JSBSim:
* Square is not used consistently : sometimes it is materialized by the number 2 appended to the unit (see your examples above), sometimes by "sq" prepended to the unit such as `metrics/Sw-sqft`
* @djlinse also filled a [bug issue on SF](https://sourceforge.net/p/jsbsim/bugs/73/) a long time ago about SFC units
* The same abbreviation "LBS" is used for pounds (weight) and pounds-force (force) so is LBS/(HR*LBS) homogeneous to HR^-1 ?
* etc.

But well, we have to live with our legacy :smiley:

**Comment by andgi** [comment]
@bcoconni No offense taken. :) And I know we have to live with our legacy. It is just that now between "M/S" and "M/SEC" which both were there already, "M/S" can be used where JSBSim needs to convert it to knot while "M/SEC" cannot.

**Pull request merged**
