### PR TITLE
Add geodetic altitude to CSV log

### PR DESCRIPTION
**Pull request by simfinite**
Hi,
I would like to have the geodetic altitude added to the CSV log. Besides my personal use cases, this may be helpful for future work on issue #184. Also, it'll simply make the log more complete.

I noticed, that the altitude AGL / distance above ground is currently being logged twice. I removed one of the entries in the second commit, because I think there shouldn't be any redundant data in the output file. If this shall be kept for backwards-compatibility, just omit the 2nd commit.

### CODE REVIEW

**Comment by simfinite** [comment]
Just realized I wasn't running all of the tests locally.. I can reproduce this now and will look into it.

**Comment by simfinite** [comment]
Ok, here is a new attempt. The failure of test case `RunCheckCases` was due to the reference log file `check_cases/orbit/logged_data/BallOut.csv` missing the new column. In order not to change the existing reference data (there are minor numerical differences when comparing to logs of the current version), I produced a new log, but only merged the new column into the existing file. Since this was a bit tricky to accomplish, here is the code I used:

```
new = pandas.read_csv("BallOut.new.csv", index_col="Time", float_precision='round_trip')
old = pandas.read_csv("BallOut.old.csv", index_col="Time", float_precision='round_trip')
merged = old.copy()
merged["Altitude Geodetic (ft)"] = new["Altitude Geodetic (ft)"]
merged.to_csv("BallOut.csv", float_format="%.16g")
```

It's a bit hard to see in a textual diff, but what this accomplishes is that all values of the old logfile are *exactly* preseverd, such that...
```
diff = merged.loc[:]-old.loc[:]
(diff == 0).all()
```
... outputs `True` for all columns but the new one (`Altitude Geodetic (ft)`).

I also found some comments listing the log columns, so I updated those.

The last commit still includes all changes to remove one of the duplicate altitude/distance AGL columns. May be omitted, if it's not desired to remove that column.

**Comment by simfinite** [comment]
hmm, the failures on Travis CI, I cannot reproduce reliably with my local setup. Although I have seen the segfault in `TestInputSocket` and also failure of `CheckScripts` occasionally when running tests in parallel with `-j8`.

**Comment by bcoconni** [comment]
You can get the same result when the property `position/geod-alt-ft` is specified in the `<output>` element : 
```xml
<output name="result.csv" type="CSV" rate="10">
  <property> position/geod-alt-ft </position>
</output>
```
So there is no reason to add C++ code to get that value (and that saves the trouble about the file `check_cases/orbit/logged_data/BallOut.csv`).

**Comment by bcoconni** [comment]
You can get the same result when the property `position/geod-alt-ft` is specified in the `<output>` element : 
```xml
<output name="result.csv" type="CSV" rate="10">
  <property> position/geod-alt-ft </position>
</output>
```
So there is no reason to add C++ code to get that value (and that saves the trouble about the file `check_cases/orbit/logged_data/BallOut.csv`).

**Comment by simfinite** [comment]
Ok, thank's for the help. I didn't know that one could specify additional properties, so that's good to know. For what it's worth, I still think removing the duplicate distance/altitude AGL would be an improvement to the C++ code, but probably not worth the trouble. Closing this now, as it's not required to be merged anymore.

**Pull request closed without merging**
