### PR TITLE
Zero initialise addrinfo and set family to IPv4

### PR DESCRIPTION
**Pull request by seanmcleod**

### CODE REVIEW

**Comment by lookingforfeng** [comment]
@seanmcleod  why always aother pull request ,is there something wrong with me.

**Comment by seanmcleod** [comment]
> @seanmcleod why always aother pull request ,is there something wrong with me.

Hi @lookingforfeng no there is nothing wrong with you, I just got impatient and hadn't heard back from you for a day or so, so I decided to go ahead and push the fix to the master branch.

**Comment by lookingforfeng** [comment]
@seanmcleod   ，，ok, jsbsim a great project. I'm glad I made a contribution  .O(∩_∩)O

**Comment by lookingforfeng** [comment]
There is a time difference between us。。 @seanmcleod

**Comment by seanmcleod** [comment]
I'm sure there is, I'm in Cape Town, so UTC+2.

**Pull request merged**
