### PR TITLE
Klein/jsbs2px4

### PR DESCRIPTION
**Pull request by bmklein5**

### CODE REVIEW

**Comment by seanmcleod** [comment]
Did you mean to submit this pull request, or was it by accident?

**Comment by seanmcleod** [comment]
@bmklein5 do you know that you've submitted a pull request to the JSBSim repo?

**Comment by bcoconni** [comment]
As @bmklein5 is not responding to the requests, the PR is closed.

**Comment by seanmcleod** [comment]
Yep, I also found an email address for him and pinged him a couple of days ago and never heard back.

**Comment by bmklein5** [comment]
Hi,

Yes that PR was accidental. Sorry don't check this email much.

-Brady
________________________________

**Pull request closed without merging**
