### PR TITLE
plots for AoA

### PR DESCRIPTION
**Pull request by gasilva**
@bcoconni told me that plots are acceptable after discussion.

### CODE REVIEW

**Comment by gasilva** [comment]
I tried to run but the following error occurred:

```
Failed to tie property simulation/output[0]/log_rate_hz to object methods
Failed to tie property simulation/output[0]/enabled to a pointer
```

**Review by seanmcleod — COMMENTED** [review]
> fix again hard work

Yep, after the previous pull request was merged you should've merged those changes into your fork to get all the changes you made via Github. Then started editing after that and then submitting this subsequent pull request.

**Comment by gasilva** [comment]
The merged code has problems. I opened the new pull request to fix it.

Guilherme A. Lima da Silva, Dr.


Em dom., 11 de jul. de 2021 às 14:53, Sean McLeod ***@***.***>
escreveu:

**Comment by gasilva** [comment]
Thank you for your help and patience.

Guilherme A. Lima da Silva


Em dom., 11 de jul. de 2021 às 15:44, Bertrand Coconnier <
***@***.***> escreveu:

**Pull request merged**
