### PR TITLE
fixing robocopy step

### PR DESCRIPTION
**Pull request by jamesford42**
paths needed to be quoted to function with spaces in directory 
the destination path was not prefixed with $(SolutionDir) 
added newlines so its actually readable in the ide

### CODE REVIEW

**Comment by jamesford42** [comment]
fixes #1118

**Comment by bcoconni** [comment]
@gallonmate, @demonixis can you comment on this ?

**Comment by seanmcleod** [comment]
Looks good to me, although I don't have Unreal installed so I haven't tested it myself.

Basically quoting the source and destination path arguments to robocopy and then it also looks like he's removed the duplication of this work from being duplicated in the project file for both debug and release builds and has it once applied for all build types?

**Comment by gallonmate** [comment]
Should be okay, thanks!

> @gallonmate, @demonixis can you comment on this ?

**Comment by bcoconni** [comment]
OK. The PR is merged.
Thanks @jamesford42 for the PR
Thanks @seanmcleod and @gallonmate for the review.

**Comment by NexRX** [comment]
I tried openning the project in VS 2022 and im getting this
`JSBSimForUnreal.vcxproj(389,4): The project file could not be loaded. There are multiple root elements. Line 389, position 4.`

Im very new to Visual Studio and all that but is `<ItemDefinitionGroup>` meant to be in it's own XML element outside the Root/`<Project>` element. Perhaps this is some VS thing i don't understand but for me at least VS 2022 doesn't want to open this up because of this unless i move it within. 

Should I raise an issue or something else going on here?

**Comment by seanmcleod** [comment]
I get the same error here with VS2022.

**Pull request merged**
