### PR TITLE
Ovehaul of the propeller code, other small fixes

### PR DESCRIPTION
**Pull request by ermarch**

### CODE REVIEW

**Comment by ermarch** [comment]
> Compute the x-offset of the center of gravity from aircraft parameters
> Use the correct value for rho, not the metric one
> Overhaul of the propeller thrust and power math: It's getting pretty close to propeller data generated with JavaProp or from other data.

**Comment by bcoconni** [comment]
@ermarch Is the PR complete, ready to be merged ? Or are you planning to commit some additional changes ?

**Comment by ermarch** [comment]
No, this should be it. I've certainly not planned anything for the 
foreseeable future.

Erik

**Comment by bcoconni** [comment]
Great ! Thanks.
Does this PR fixes the issue #173 as well ? If so, could you please tell the issue poster that the feature request has been addressed ?
Thanks.

**Comment by ermarch** [comment]
On 9/15/20 11:10 PM, Bertrand Coconnier wrote:
> Great ! Thanks.
> Does this PR fixes the issue #173 
> <https://github.com/JSBSim-Team/jsbsim/issues/173> as well ? If so, 
> could you please tell the issue poster that the feature request has been 
> addressed ?

No this issue has not been solved with this patch since it needs some 
considerations on how to keep it backwards compatible:

AeromatiC++ can output it's parameters to a file and read them back for 
a second run, for instance when AeromatiC++ has been improved. And 
messing with the number of inputs is a bit tricky at the moment since it 
just reads the file as if it where the standard input.

Erik

**Comment by ermarch** [comment]
The estimation code for the number of blades has changes though and this 
also influences the propeller material: wood, aluminum or carbon fiber 
for calculation of the propeller inertia.

**Pull request merged**
