### PR TITLE
run in win10_x64 vs2019

### PR DESCRIPTION
**Pull request by lookingforfeng**
run in win10_x64 vs2019，to fix issue #254

### CODE REVIEW

**Comment by bcoconni** [comment]
@seanmcleod I have nominated you as the assignee for this PR as you are much more qualified than myself to review it 😄

**Comment by lookingforfeng** [comment]
you are right ,i meet another trouble

**Comment by lookingforfeng** [comment]
@seanmcleod      all  i  did is want to make the function getaddrinfo() work right, when i add the ws2_32.lib to the project,  it can compilation and link successfully, but the getaddrinfo() fucntion can not get the expected reslut.

**Comment by lookingforfeng** [comment]
@seanmcleod  i am sure there is no lib named ws2_32.lib

**Pull request closed without merging**
