### PR TITLE
MEX build issue on Windows

### PR DESCRIPTION
**Pull request by bcoconni**
As reported by @fkg-ctsi (see below), the build of the MATLAB S-function is broken since we allowed JSBSim to be built as a DLL. In order to avoid the build failing when JSBSim is compiled as a static library, the flag `JSBSIM_STATIC_LINK` is now passed to the `mex` compiler.

### Discussed in https://github.com/JSBSim-Team/jsbsim/discussions/734

<div type='discussions-op-text'>

<sup>Originally posted by **fkg-ctsi** September 23, 2022</sup>
Hi there!
Firstly, thank you so much for all of the continued development and support over the years. This project has really helped make this industry more accessible!

I have a (likely) noob question re: compiling the S-Function using MEX.

I've been following the guide, and when I get to the step to compile with mex, I get a large link error dump. 

Here is a snippet:

```
Error using mex
   Creating library JSBSim_SFunction.lib and object JSBSim_SFunction.exp
LINK : warning LNK4217: symbol '??0SGPath@@QEAA@P6A?AUPermissions@0@AEBV0@@Z@Z (public: __cdecl
SGPath::SGPath(struct SGPath::Permissions (__cdecl*)(class SGPath const &)))' defined in
'JSBSim.lib(sg_path.obj)' is imported by 'JSBSim_SFunction.obj' in function '"void __cdecl
mdlInitializeConditions(struct SimStruct_tag *)" (?mdlInitializeConditions@@YAXPEAUSimStruct_tag@@@Z)'
...
...
JSBSim_SFunction.mexw64 : fatal error LNK1120: 13 unresolved externals
```

For reference, I am using VS Community 2019, and Matlab/Simulink 2022b (Really hoping that this isn't the issue)

Admittedly, I am a MEX noob and only functional in C++, but would really appreciate a nudge in where to start investigating a path forwards.

Thanks!

</div>

### CODE REVIEW

**Comment by bcoconni** [comment]
@agodemar would you mind checking if the S-Function compiles again with the Windows command line from `matlab/JSBSimSimulinkCompile.m` ? Thanks.

**Comment by agodemar** [comment]
@bcoconni I have merged your recent fix and let you know if the Matlab v2022b compiles

**Comment by agodemar** [comment]
@bcoconni 
After merging your last modification I configured the compilation of JSBSim on Windows from the sources using CMake:
JSBAim_Matlab_01
JSBAim_Matlab_02

Then I successfully compiled both JSBSim.exe and JSBSim_SFunction.mexw64 on Windows:

JSBAim_Matlab_03
JSBAim_Matlab_04

Finally, I copied all the necessary files in JSBSim root directory and successfully tested the example Simulink model `ex737cruise.slx`, which includes the latest modifications in terms of I/O signal configurations via an XML file (see `ex737cruise_io.xml`)

JSBAim_Matlab_05
JSBAim_Matlab_06
JSBAim_Matlab_07
JSBAim_Matlab_08
JSBAim_Matlab_09
JSBAim_Matlab_10

Please guide me in the finale step: take the release version incorporating this latest feature and compile the M-file `JSBSimSimulinkCompile.m`. It looks like VS 2022 Community Edition compiles it fine. Need to check if the same happens using Matlab's MEX compiler.

**Comment by bcoconni** [comment]
Thanks @agodemar for testing the procedure to build the S-Function with CMake.

> Please guide me in the finale step: take the release version incorporating this latest feature and compile the M-file `JSBSimSimulinkCompile.m`. It looks like VS 2022 Community Edition compiles it fine. Need to check if the same happens using Matlab's MEX compiler.

For this part, I guess you'll need to follow the steps described in our [MATLAB README](https://github.com/JSBSim-Team/jsbsim/blob/master/matlab/README.md) (which was written from your input in the issue #491 😊). Of course, you can skip the part about downloading and installing JSBSim from the Windows installer `JSBSim-1.1.12-setup.exe` as you already built the DLL.

**Comment by agodemar** [comment]
@bcoconni you mean that these modification is already bundled in the current setup package downloadable from the release section?

Don't we have to wait that the CI workflow makes a new package?

**Comment by bcoconni** [comment]
> @bcoconni you mean that these modification is already bundled in the current setup package downloadable from the release section?

@agodemar No, I meant to ask if you could build the S-Function from scratch as per the instructions from our [MATLAB README](https://github.com/JSBSim-Team/jsbsim/blob/master/matlab/README.md). This is a different means to build the S-Function than using CMake. The point is to check that the default parameters of the file [`matlab/JSBSimSimulinkCompile.m`](https://github.com/JSBSim-Team/jsbsim/blob/master/matlab/JSBSimSimulinkCompile.m) are correctly set in order to build the S-Function without the user needing to tweak the file content.

**Pull request merged**
