### PR TITLE
Python plot example - Clean PR

### PR DESCRIPTION
**Pull request by gasilva**
a clean PR in a new branch to include aoa.py in examples

### CODE REVIEW

**Comment by seanmcleod** [comment]
Hmm, but there are 6 files changed in this pull request, not just the sample python file.

**Comment by gasilva** [comment]
> Hmm, but there are 6 files changed in this pull request, not just the sample python file.

Git's logic is a mess. I do not know how to fix it. I got a commit from the past..the last one that was accepted.

**Comment by seanmcleod** [comment]
Which commit did you use for the basis of the new branch? Maybe it wasn't far enough back?

**Comment by gasilva** [comment]
What is the commit that shall be the base of the branch?

Em dom., 27 de jun. de 2021 às 14:20, Sean McLeod ***@***.***>
escreveu:

**Comment by gasilva** [comment]
All commits before the commit I used have 6 files changed.
I can not choose another and have less files.

Guilherme


Em dom., 27 de jun. de 2021 às 14:21, Guilherme Araujo Lima da Silva <
***@***.***> escreveu:

**Comment by seanmcleod** [comment]
Now there are 10 changed files :wink

**Pull request closed without merging**
