### PR TITLE
Test rotor udp

### PR DESCRIPTION
**Pull request by ahs4**

### CODE REVIEW

**Comment by seanmcleod** [comment]
@ahs4 we really need a description of what this pull request entails in order to consider it. You can't simply dump 23 commits with no overall description and assume the JSBSim maintainers are going to go through them trying to figure out what you're trying to achieve and whether any of it makes sense in terms of merging into the main JSBSim branch.

**Comment by ahs4** [comment]
Can we delete this pull request and shall provide a more clear one

**Comment by ahs4** [comment]
Can we delete this pull request and shall provide a more clear one

**Comment by ahs4** [comment]
Can we delete this pull request and shall provide a more clear one

**Comment by ahs4** [comment]
Can we delete this pull request and shall provide a more clear one

**Comment by seanmcleod** [comment]
Yep. Also if you're not 100% certain with regards to your pull request you can also open a discussion item first to discuss before you submit a pull request.

**Pull request closed without merging**
