### PR TITLE
fix: toupper is not a member of std

### LINKED ISSUE #1019: MSVC: toupper is not a member of std
**I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => **Please do not submit support request here**, see note at the top of this template.

**Describe the issue**
Using MSVC 14.0 (2015), I receive the following error during compilation:
`error C2039: 'toupper': is not a member of 'std'`

**What is the current behavior?**
Compilation error:
`error C2039: 'toupper': is not a member of 'std'`

**What is the expected behavior?**
Compile without errors

**Please tell us about your environment:**
 - OS: Windows 10
 - JSBSim: v1.2.0
 - Language: C++

**Other information**
The bug is simple to resolve.
I'll create a PR ASAP

### PR DESCRIPTION
**Pull request by carlocorradini**
Fix #1019

### CODE REVIEW

**Review by bcoconni — CHANGES_REQUESTED** [review]
As @seanmcleod [already said](https://github.com/JSBSim-Team/jsbsim/issues/1019#issuecomment-1902681856), the code currently in `master` successfully compiles on all supported platforms (MSVC 2019 & 2022, MinGW, Mac OSX and Linux) while yours fails on all platforms but MSVC.

So I'd suggest you revisit this patch so that it compiles everywhere (and please no `#ifdef`).

**Comment by carlocorradini** [comment]
@bcoconni Done
`std::toupper` is overloaded so there is the need to help the compiler choose the correct one.
See https://stackoverflow.com/questions/7131858/stdtransform-and-toupper-no-matching-function

**Comment by seanmcleod** [comment]
I reran the github build process and no compiler errors now across all compilers and platforms.

Out of interest what are you using JSBSim for and is there a particular need to use the fairly old MSVC 2015 compiler?

**Comment by carlocorradini** [comment]
Done.
It works! 🥳🤯
Let's see the workflows...

**Pull request merged**
