### PR TITLE
python scripts examples

### PR DESCRIPTION
**Pull request by gasilva**
To implement three python scripts to give an example of powerful integration between jsbsim and python. For engineering purposes may be the most recommended tool.

All have graphics outputs but they can be changed to a table format.
The plot are more useful basically.

- `catalog.py`: 
List properties of a script
This is good to know which variable to read and write

- `runScriptLongFlight.py`
Calculation required by aircraft icing enginering
Information required to calculate fuel consuption in leveled flight with no slats or flaps in order to provide data for mission profile analysis

- `runJSBSimFuelMach.py`
Calculation required by aircraft icing enginering
Find the optimum value for fuel consumption 
For greatest distance - low AoA and high speed (Carson cruise)
For greatest time - high AoA and low speed (miminum power required)

The aoa.py appeared in the commit without adding it.
It appears to be the last version the in the github. I checkout the file before PR.

### CODE REVIEW

**Comment by gasilva** [comment]
I do not want to change `aircraft/global5000/global5000.xml` and `examples/python/aoa.py`
I did not add them to the commit but they appeared
How to keep the version of GitHub repository?
How to take them out from the PR?

**Comment by seanmcleod** [comment]
I'm not sure why your pull requests often seem to have this issue with including changes to files that aren't relevant. This is the procedure I use.

Before starting work on a new feature I sync up my fork's master branch with the official JSBSim master branch.

```sh
git fetch upstream
git merge upstream/master
``` 

Then I create a new branch from this up to date master branch and push commits in this new branch. When I've finished testing then I generate a pull request from this new branch.

Here are my last 3 pull requests showing how only the relevant files appear.

https://github.com/JSBSim-Team/jsbsim/pull/476/files
https://github.com/JSBSim-Team/jsbsim/pull/471/files
https://github.com/JSBSim-Team/jsbsim/pull/470/files

And once the pull request has been accepted and merged into the official JSBSim repo then I perform the steps above to sync up my master branch in my fork again.

**Comment by gasilva** [comment]
(base) gasilva@kamino jsbsim % git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(base) gasilva@kamino jsbsim % git merge upstream/master
merge: upstream/master - not something we can merge
(base) gasilva@kamino jsbsim %

**Comment by seanmcleod** [comment]
How is your repo configured?

```sh
PS C:\source\jsbsim> git remote -v
origin  https://github.com/seanmcleod/jsbsim.git (fetch)
origin  https://github.com/seanmcleod/jsbsim.git (push)
upstream        https://github.com/JSBSim-Team/jsbsim.git (fetch)
upstream        https://github.com/JSBSim-Team/jsbsim.git (push)
```

This is the original documentation I used a couple of years ago to get things configured and the process to use.

https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by gasilva** [comment]
I cannot resolve the conflicts here...the buttom is off for me...could you do it? @seanmcleod

**Comment by gasilva** [comment]
```
(base) gasilva@kamino jsbsim % git remote -v
origin	https://github.com/gasilva/jsbsim.git (fetch)
origin	https://github.com/gasilva/jsbsim.git (push)
```

**Comment by seanmcleod** [comment]
> Mine does not have upstream

Yep, so take a look at the documentation link I posted above.

**Comment by gasilva** [comment]
After `git remote add upstream https://github.com/JSBSim-Team/jsbsim.git`

```
(base) gasilva@kamino jsbsim % git remote -v
origin	https://github.com/gasilva/jsbsim.git (fetch)
origin	https://github.com/gasilva/jsbsim.git (push)
upstream	https://github.com/JSBSim-Team/jsbsim.git (fetch)
upstream	https://github.com/JSBSim-Team/jsbsim.git (push)
```

**Comment by seanmcleod** [comment]
Have you looked at the changes you're tying to push?

https://github.com/JSBSim-Team/jsbsim/pull/479/files

**Comment by gasilva** [comment]
> Have you looked at the changes you're tying to push?
> 
> https://github.com/JSBSim-Team/jsbsim/pull/479/files

it is all wrong...I am lost here sorry

**Pull request closed without merging**
